# Generated by Django 4.1.7 on 2023-03-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='user_profile/photos/default.png', upload_to='user_profile/photos/', verbose_name='photo'),
        ),
    ]
