# Generated by Django 4.1.7 on 2023-03-13 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='last name')),
                ('address', models.CharField(db_index=True, max_length=100, verbose_name='address')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(db_index=True, max_length=15, verbose_name='phone number')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='order date')),
                ('status', models.CharField(choices=[('o', 'ordered'), ('p', 'in process'), ('d', 'done'), ('c', 'cancelled')], default='o', max_length=1, verbose_name='status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='service.customer', verbose_name='customer')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='service.order', verbose_name='orders')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='service.service', verbose_name='service')),
            ],
        ),
    ]
