# Generated by Django 4.1.7 on 2023-03-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_customer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='schematic',
            field=models.ImageField(blank=True, null=True, upload_to='service/schematics/', verbose_name='schematic'),
        ),
    ]
