# Generated by Django 4.1.7 on 2023-03-21 14:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=4000, null=True, verbose_name='description'),
        ),
    ]
